
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 12 23:05:00 EDT 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A4Symbol {
  /* terminals */
  public static final int READ = 5;
  public static final int ELSE = 4;
  public static final int PLUS = 15;
  public static final int INT = 24;
  public static final int NOTEQUAL = 19;
  public static final int SEMI = 13;
  public static final int END = 8;
  public static final int RETURN = 2;
  public static final int IF = 3;
  public static final int WRITE = 6;
  public static final int ID = 10;
  public static final int EQUALTO = 18;
  public static final int NUM = 17;
  public static final int BEGIN = 7;
  public static final int STRING = 26;
  public static final int COMMA = 23;
  public static final int MULT = 20;
  public static final int EOF = 0;
  public static final int MAIN = 9;
  public static final int DIV = 21;
  public static final int MINUS = 16;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int QSTRING = 14;
  public static final int REAL = 25;
  public static final int LEFTPAREN = 11;
  public static final int RIGHTPAREN = 12;
}

